apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
        - name: go-hello
          imagePullPolicy: Never
          image: go-hello
          ports:
            - containerPort: 9090
