apiVersion: v1
kind: Service
metadata:
  name: go-hello
spec:
  selector:
    app: go-hello
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
  type: LoadBalancer
  externalIPs:
    - 192.168.67.2